// <auto-generated />
using Asp.netMVCCRUD.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Asp.netMVCCRUD.Migrations
{
    [DbContext(typeof(ImoneContext))]
    partial class ImoneContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Asp.netMVCCRUD.Models.Imone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AktualiVeikla")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Apskritis")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BlogasElPastas")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ElPastas")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ImonesKodas")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("KitaInfo")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TelNr")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("VMVT")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Imones");
                });
#pragma warning restore 612, 618
        }
    }
}
